### ISSUE TITLE
Register configured connector

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/debezium-ui-poc#11]
@rk3rn3r, creating this so to prepare the hand-over of the backend work to you. What's essentially missing now is the actual registration call to Kafka Connect:

* Add a new endpoint for PUT /api/connector/ in our service
* Use the JDK 11 HTTP client to invoke the KC REST API for registering the connector
* Work with @mdrillin to get this hooked up and integrated with the client-side UI

Note there's a general architectural question which we should discuss: atm. the backend server itself embeds the Debezium connectors and instantiates them in order to invoke their validation functionalities. This creates potential for a mismatch between the Debezium version deployed in the actual KC and the UI backend server (e.g. when it comes to new config options). When it comes to integration with Strimzi, there'd be no way around this anyways, as there would be no KC running yet at the point in time when the UI backend is invoked. But as we're there in a more controlled and managed environment anyways, we just might assume version parity and it's not a problem. When it comes to plain KC usage (i.e. without operator) though, as we aim at for the PoC, we also might consider exposing validation functionality (or perhaps even the entire backend?) via that custom REST endpoint facility in KC you recently discovered.

I think that's all fine for the PoC, so we just might postpone this discussion. I just wanted to bring it up, to make you aware of this issue and in case you got any thoughts around this.

**Comment by rk3rn3r** [comment]
This took some time as the include/exclude list task had some priority and I'm still working on the unit tests of the incubator connector changes. The code is ready but the backend unit tests with quarkus and testcontainers were having problems. once the incubator include/exclude changes are ready I would like to go no with that task.

About the architecture question: instead of including the connectors we could add custom endpoints to Kafka Connect and pass the requests to KCD REST API to validate data. I am also working on a PoC of that, but not really started on that one as I am still busy with the other topics.

**Comment by gunnarmorling** [comment]
> we could add custom endpoints to Kafka Connect

Ok, that sounds great in the long run. I think for the PoC we could go the simpler route and continue with relying on connectors being embedded into the UI backend so we can obtain the metadata from there? OTOH, if it's a trivial matter to add the custom KC REST resource, we can try it, but I wouldn't sink multiple PoC days on that.

**Comment by rk3rn3r** [comment]
Done with #26
