### ISSUE TITLE
Use titles on step content areas consistently

### ISSUE THREAD

**Issue by mdrillin** [debezium/debezium-ui-poc#200]
Some wizard steps have a title at the top of the content area, and others do not.  
Suggest using a title at the top of each step.

**Comment by mdrillin** [comment]
@nding-anges - I'm not sure I'm interpretting this one correctly.  On UX doc there was comment on the connector type page "consider using form label".  Did you mean to put a title at the top of the page?  If so, should each step of the wizard have a similar title at the top?

**Comment by nding-anges** [comment]
Hi@mdrillin -I just double-check the review doc, there is no comment about adding a title at the top of content for each step. I think that for the connector type page, Lucia has suggested using the tiles component instead of selectable cards: https://www.patternfly.org/v4/components/tile. From my understanding, the label will be on those disable connectors, which to indicated information like: ' not available for now' or 'coming soon', since the visual of disabling is not quite clear

**Comment by mdrillin** [comment]
@nding-anges I didn't understand item 3, and thought maybe it was asking for a title.  The tile component is still in beta, so I didn't think we should use it yet?

**Comment by nding-anges** [comment]
Hi, Mark. Just confirmed with Lucia. The comment about the' Label' is suggesting to have a field label describing the content of the tiles below...something like "Connector type" (using the field label text style, not the label component). I  think the 3rd item should not be there. It might be a mistake in labeling.

**Comment by mdrillin** [comment]
I'll close this issue then - the request to use 'tiles' component is covered in issue #159
