### ISSUE TITLE
Add 'optional' label to the additional properties

### ISSUE THREAD

**Issue by mdrillin** [debezium/debezium-ui-poc#202]
Add optional label as shown below, for the grouped properties

![Debezium UI - UXD Feedback (3)](https://user-images.githubusercontent.com/1820403/96008067-c86a4d80-0e04-11eb-9056-820996fa1410.png)

**Comment by nding-anges** [comment]
Thanks for opening this issue @mdrillin I will check the label design with PF4 team first in terms of consistency.We could mark this issue with low priority for now. And I'll come up with the final design later.

**Comment by mdrillin** [comment]
Reached out to UX via email on this one.

**Comment by nding-anges** [comment]
Just reply to the mail. After review the design again and discuss with the design team, I am hoping to update the design and use the asterisk (*) to indicate the required steps since it is more simple and more consistent with PatternFly. WDYT? See a screenshot below. 
<img width="891" alt="屏幕快照 2020-12-08 下午1 55 20" src="https://user-images.githubusercontent.com/34368385/101446674-ad2c4200-395e-11eb-8fdb-e8bb7101c4c0.png">

**Comment by mdrillin** [comment]
Closing this - PR #225 was merged
