### ISSUE TITLE
Mongo filter responses include 'null.' in namespace names

### ISSUE THREAD

**Issue by mdrillin** [debezium/debezium-ui-poc#267]
The response for the service call '/api/connector-types/mongodb/validation/filters' is including 'null.' in the namespace names.  See below for an example payload and the response. 

**payload**:
 {
  "mongodb.hosts":"dbzui-db-mongo:27017",
  "mongodb.members.auto.discover":true,
  "mongodb.poll.interval.ms":30000,
  "mongodb.user":"debezium",
  "mongodb.password":"***",
  "mongodb.name":"inventory",
  "connector.name":"mongoTest",
  "mongodb.connect.timeout.ms":10000,
  "connect.backoff.initial.delay.ms":1000,
  "connect.backoff.max.delay.ms":120000,
  "mongodb.authsource":"admin",
  "connect.max.attempts":16,
  "mongodb.server.selection.timeout.ms":30000,
  "mongodb.socket.timeout.ms":0
 }

**response**:
 { "matchedCollections":[
     {"name":"products","namespace":"null.inventory"},
     {"name":"customers","namespace":"null.inventory"},
     {"name":"orders","namespace":"null.inventory"},
     {"name":"system.sessions","namespace":"null.config"},
     {"name":"transactions","namespace":"null.config"}],
   "propertyValidationResults":[],"status":"VALID"
 }

**Comment by rk3rn3r** [comment]
Hey, sorry for the late reply! Because of other things fall behind because of my sickness in January I had different topics and missed replying on time. Sorry, sorry!
The structure is: `replicaSet`.`databaseName`.`collectionName`. When you get this as `null` it means you don't have a replicaSet configured for your MongoDB instance. But a replicaSet is needed when using the MongoDB connector.

I have to think about if we can validate this in the main Debezium code. @gunnarmorling WDYT?

**Comment by gunnarmorling** [comment]
Yeah, replicaSet should never be null really. Not sure how the connector
would even work in that case?

>

**Comment by rk3rn3r** [comment]
It doesn't work. But it validates in Connector#validate which allows the connector setup process in the UI to continue and then we see invalid output in the Filters step.

**Comment by gunnarmorling** [comment]
Ah, gotcha. Yeah, that shouldn't be accepted input then.

>

**Comment by rk3rn3r** [comment]
@mdrillin that is the Jira task for this issue: https://issues.redhat.com/browse/DBZ-3029
